#spring:
#  application:
#    name: service-consumer
#
#  cloud:
#    nacos:
#      discovery:
#        #        如果使用docker-compose部署,这里就是docker容器地址
#        server-addr: 127.0.0.1:8848
#
#server:
#  port: 8899
#
## 健康检查，判断实例是否健康 /actuator/nacos-discovery
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#user:
#  name: hahaha